version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dailyschedule
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  backend:
    container_name: dailyschedule_backend
    build:
      context: .
      dockerfile: dockerfile
    networks:
      - default
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - postgres
volumes:
  postgres_data: