version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dailyschedule
      POSTGRES_USER: daily
      POSTGRES_PASSWORD: daily
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    networks:
      - default
  django:
    build: .
    command: python manage.py runserver
    networks:
      - default
