version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dailyschedule
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  backend:
    image: backend:latest
    networks:
      - default
    ports:
      - "8000:8000"
    volumes:
      - .:/core
    depends_on:
      - postgres
  frontend:
    image: frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  postgres_data:
